on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Test Coveralls

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
    
    - name: Run tests and generate coverage
      if: success() || failure()
      run: npm test
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    
    - name: Upload coverage to Coveralls
      if: success() || failure()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

  finish:
    needs: test
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
