on: ["push", "pull_request"]

name: Test Coveralls

jobs:
  test:
    runs-on: window-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
    
    - name: Run tests and generate coverage
      run: npm test
    
    - name: Upload coverage to Coveralls
      run: npm run coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
