on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Test Coveralls

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
    
    - name: Run tests and generate coverage
      run: npm test
    
    - name: Upload coverage to Coveralls
      run: npm run test:coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
